---
- name: Converge
  hosts: all
  become: true
  vars:
    stack_name: sample-webapp
    stack_src_dir: ../../../../stacks/sample-webapp
    healthcheck_url: http://127.0.0.1:8080/
  roles:
    - docker_engine
    - compose_stack
